bot/urls.py
from django.urls import path, include

from . import views

app_name = 'bot'

messages_urls = ([
    path('', views.IgnoranceList.as_view(), name='list'),
    path(
        '<uuid:uuid>/',
        views.MessageTemplateEdit.as_view(),
        name='template-edit'
    ),
    path(
        '<uuid:uuid>/reset/',
        views.ResetMessageTemplate.as_view(),
        name='template-reset'
    ),
], 'messages')

urlpatterns = [
    path('bot/gl', views.gl),
    path('messages/', include(messages_urls)),
]

sportcrm/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings

app_name = 'sportcrm'
if not settings.BACKGROUND_MODE:
    urlpatterns = [
        path('admin/', admin.site.urls, name='admin'),
        path('', include('crm.urls')),
        path('', include('bot.urls')),
        path('', include('social_django.urls', namespace='social')),
        path(
            'api/v1/',
            include(('crm.urls_api', 'api-v1'), namespace='api-v1')
        ),
        path(
            'api/v1/',
            include(('bot.urls_api', 'bot-api-v1'), namespace='bot-api-v1')
        ),
        path(
            'qr_code/',
            include(('qr_code.urls', 'qr_code'), namespace="qr_code")
        ),
        path('', include('gcp.urls')),
        path(
            '',
            include(
                ('vk_group_app.urls', 'vk_group_app'),
                namespace="vk_group_app"
            )
        ),
    ]
else:
    urlpatterns = [
        path('', include('gcp.background_urls')),
        path('', include('bot.background_urls')),
    ]

vk_group_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('vk_group_app/', views.VkPageView.as_view(), name='vk-app-frame'),
    path('vk_group_app/mark/', views.MarkClient.as_view(), name='mark-client'),
    path(
        'vk_group_app/unmark/',
        views.UnMarkClient.as_view(),
        name='unmark-client'
    ),
    path(
        'vk_group_app/bot-params/',
        views.CompanyBotParams.as_view(),
        name='bot-params'
    ),
]

vk_group_app/models.py
from django.db import models

# Create your models here.

vk_group_app/views.py
from datetime import date, datetime, timedelta

from django.db.models import Count
from django.utils.decorators import method_decorator
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import TemplateView
from django_multitenant.utils import set_current_tenant, get_current_tenant
from rest_framework import status
from rest_framework.generics import CreateAPIView, GenericAPIView
from rest_framework.response import Response
from gcp.tasks import enqueue

from contrib.vk_utils import get_vk_user_info
from crm.models import Attendance, Client, Company, Event, EventClass
from vk_group_app.const import VK_USER_GUEST, VK_USER_ADMIN
from vk_group_app.serializers import (
    VkActionSerializer,
    VkAdminOptionsSerializer,
)
from vk_group_app.utils import signed_clients_display


@method_decorator(xframe_options_exempt, name='dispatch')
class VkPageView(TemplateView):
    vk_group_id: int = 0
    vk_user_id: int = None

    def get(self, request, *args, **kwargs):
        # iframe init params: https://vk.com/dev/apps_init

        try:
            self.vk_group_id = int(request.GET.get('group_id', 0))
        except (ValueError, KeyError, TypeError):
            pass

        # viewer_id is always present
        self.vk_user_id = int(request.GET['viewer_id'])
        self.app_id = int(request.GET['api_id'])
        self.vk_user_type = int(request.GET['viewer_type'])

        try:
            self.setup_tenant()
        except ValueError:
            # Request may not have tenant, if it was called from app page or
            # admin launch application for the first time
            pass

        return super().get(request, *args, **kwargs)

    def get_template_names(self):
        # Application is run from group
        if self.vk_group_id != 0:
            # User is not in group
            if self.vk_user_type == VK_USER_GUEST:
                return 'vk_group_app/vk_enter_in_group.html'
            else:
                return 'vk_group_app/vk_sign_up.html'
        else:
            return 'vk_group_app/vk_app_promo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.vk_group_id != 0:
            # User is not in group
            if self.vk_user_type == VK_USER_GUEST:
                context.update(self.get_enter_page_context())
            else:
                context.update(self.get_user_page_context())
                if self.vk_user_type == VK_USER_ADMIN:
                    context.update(self.get_admin_page_context())
        else:
            context.update(self.get_app_page_context())

        return context

    def get_app_page_context(self):
        return {
            'app_id': self.app_id
        }

    def get_enter_page_context(self):
        return {
            'vk_group': self.vk_group_id
        }

    def get_admin_page_context(self):
        context_data = {
            'app_id': self.app_id,
            'is_admin': True,
            'has_company': True,
            'has_access_token': False,
            'vk_group': self.vk_group_id
        }
        company = get_current_tenant()
        if company is None:
            context_data['has_company'] = False
        else:
            context_data['has_access_token'] = (
                company.vk_access_token is not None
            )
            context_data['vk_access_token'] = company.vk_access_token
            context_data['vk_confirmation_token'] = \
                company.vk_confirmation_token

        return context_data

    def get_user_page_context(self):
        company = get_current_tenant()
        if company is None:
            return {}

        client = Client.objects.filter(vk_user_id=self.vk_user_id).first()
        day_start = date.today()
        day_end = day_start + timedelta(weeks=1)

        # Prepare events
        events = []
        for ec in EventClass.objects.in_range(day_start, day_end):
            events.extend(list(ec.get_calendar(day_start, day_end).values()))
        events = sorted(
            events, key=lambda x: datetime.combine(x.date, x.start_time))

        # Prepare event class one time visit price
        ec_otv_price = {}
        for event in events:
            ec_id = event.event_class_id
            if ec_id in ec_otv_price:
                continue

            ec_otv_price[ec_id] = event.event_class.otv_price

        # Prepare count of clients signed for one event
        a_count = (
            Attendance.objects
            .filter(event__in=[x.id for x in events], signed_up=True)
            .annotate(client_count=Count('event'))
            .values('event_id', 'client_count')
        )
        event_signed_count = {
            x['event_id']: x['client_count'] for x in a_count
        }

        # Find events where this client is marked
        my_events = []
        if client:
            my_events = Attendance.objects.filter(
                event__in=[x.id for x in events],
                signed_up=True,
                client=client
            ).values_list('event_id', flat=True)

        return {
            'is_admin': False,
            'vk_id': self.vk_user_id,
            'vk_group': self.vk_group_id,
            'client': client,
            'my_events': my_events,
            'events': events,
            'ec_otv_price': ec_otv_price,
            'event_signed_count': event_signed_count
        }

    def setup_tenant(self):
        try:
            company = Company.objects.get(vk_group_id=self.vk_group_id)
        except Company.DoesNotExist:
            raise ValueError()

        set_current_tenant(company)


class EventMixin:
    def get_event(self, serializer):
        event_date = date(
            serializer.validated_data['year'],
            serializer.validated_data['month'],
            serializer.validated_data['day']
        )
        event = Event.objects.get_or_virtual(
            serializer.validated_data['eventClassId'], event_date)
        if not event.id:
            event.save()

        return event


class CompanyMixin:
    def get_company(self, serializer):
        try:
            return Company.objects.get(
                vk_group_id=serializer.validated_data['vkGroup'])
        except Company.DoesNotExist:
            return None

    def set_tenant(self, serializer):
        company = self.get_company(serializer)
        if not company:
            raise ValueError('No company found for vk group')

        set_current_tenant(company)


class ClientMixin:
    def get_client(self, serializer) -> Client:
        client = Client.objects.filter(
            vk_user_id=serializer.validated_data['vkId']).first()
        if not client:
            client = self.create_client(serializer)
        return client

    def create_client(self, serializer):
        vk_id = serializer.validated_data['vkId']
        client = Client.objects.create(vk_user_id=vk_id)
        info = get_vk_user_info(vk_id)[vk_id]
        client.name = f'{info["first_name"]} {info["last_name"]}'
        bdate = info.get('bdate')
        if bdate:
            try:
                client.birthday = datetime.strptime(bdate, '%d.%m.%Y')
            except ValueError:
                pass
        client.save()
        return client


class MarkClient(ClientMixin, CompanyMixin, EventMixin, GenericAPIView):

    serializer_class = VkActionSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        try:
            self.set_tenant(serializer)
            client = self.get_client(serializer)
            event: Event = self.get_event(serializer)
            client.signup_for_event(event)
            enqueue('notify_manager_about_signup', event.id, client.id)
        except Exception as exc:
            return Response(
                {'success': False, 'error': str(exc)},
                status=status.HTTP_200_OK
            )

        return Response({
            'success': True,
            'signedCount': signed_clients_display(event.signed_up_clients)
        }, status=status.HTTP_201_CREATED)


class UnMarkClient(ClientMixin, CompanyMixin, EventMixin, CreateAPIView):
    serializer_class = VkActionSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        try:
            self.set_tenant(serializer)
            client = self.get_client(serializer)
            event: Event = self.get_event(serializer)
            client.cancel_signup_for_event(event)
            enqueue('notify_manager_about_unsignup', event.id, client.id)
        except Exception as exc:
            return Response(
                {'success': False, 'error': str(exc)},
                status=status.HTTP_200_OK
            )

        return Response({
            'success': True,
            'signedCount': signed_clients_display(event.signed_up_clients)
        }, status=status.HTTP_201_CREATED)


class CompanyBotParams(CompanyMixin, CreateAPIView):
    serializer_class = VkAdminOptionsSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        company = self.get_company(serializer)
        if not company:
            return Response(
                {
                    'success': False,
                    'error': 'Нет компании привязанной к сообществу'
                },
                status=status.HTTP_200_OK
            )

        company.vk_access_token = serializer.validated_data['accessToken']
        company.vk_confirmation_token = serializer.validated_data['botConfirm']
        company.save()

        return Response({'success': True}, status=status.HTTP_200_OK)

vk_group_app/templates/vk_group_app/vk_app_promo.html
{% load html_helper %}
<html lang="ru">
<head>
  {% css 'css/vkui.css' %}
</head>

<body>
<div class="page_block">
  <div class="page_block_header">
    Приложение sportcrm
  </div>
  <div style="text-align: center;">
    <div style="padding-top: 10px; padding-bottom: 10px;">
      Приложение для интеграции с
      <a href="https://sportadmin.ru" target="_parent">sportadmin.ru</a>
    </div>
    <div style="padding-bottom: 10px;">
      <a
        class="flat_button"
        href="https://vk.com/add_community_app.php?aid={{ app_id }}"
        target="_parent"
      >
        Установить приложение
      </a>
    </div>
  </div>
</div>
</body>
</html>

vk_group_app/templates/vk_group_app/vk_enter_in_group.html
{% load bootstrap4 html_helper %}
<html lang="ru">
<head>
  {% css 'css/vkui.css' %}
  {% css 'css/simple-grid.min.css' %}
  {% bootstrap_jquery %}
  <script
    type="text/javascript" src="https://vk.com/js/api/xd_connection.js?2"
  ></script>
  <script type="text/javascript">
    $(function () {
      VK.init(
        function () {
        },
        function () {
        },
        '5.92'
      );
    });
  </script>
</head>

<body>
<div class="page_block">
  <div class="page_block_header">
    Приложение sportcrm
  </div>
  <div class="msg info_msg">
    <div class="msg_text">
      Приложение доступно только пользователям группы. <a href="https://vk.com/club{{ vk_group }}" target="_parent">Вступайте в группу</a>, и
      пользуйтесь этим приложением.
    </div>
  </div>
  <div class="page_block_info">
    <a class="flat_button" href="https://vk.com/club{{ vk_group }}" target="_parent">
      Вступить в группу
    </a>
  </div>
</div>
</body>
</html>

vk_group_app/templates/vk_group_app/vk_sign_up.html
{% load bootstrap4 html_helper humanize %}
<html lang="ru">
<head>
  {% css 'css/vkui.css' %}
  {% css 'css/simple-grid.min.css' %}
  <link
    rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous"
  >
  {% bootstrap_jquery %}
  <script
    type="text/javascript" src="https://vk.com/js/api/xd_connection.js?2"
  ></script>
  <script type="text/javascript">
    let defaultParams = {
      vkId: {{ vk_id }},
      vkGroup: {{ vk_group }}
    };

    function iframeResize() {
      let currentSize = 0;
      return function () {
        let newSize = $('#main-data').height();
        {% if is_admin %}
          let $admin = $('#admin-data');
          if ($admin) {
            newSize += $admin.height();
          }
        {% endif %}
        if (newSize !== currentSize) {
          VK.callMethod('resizeWindow', 0, newSize + 30);
          currentSize = newSize;
        }
      }
    }

    function markToEvent(eventParams) {
      let params = {
        ...defaultParams,
        ...eventParams
      };
      $.post({
        url: "{% url "vk_group_app:mark-client" %}",
        data: params,
        success: function (data) {
          if (data.success) {
            let selectorArgs = eventParamsToSelector(eventParams);
            let selectorPrefix = `div.container ${selectorArgs}`;
            $(`${selectorPrefix} button.mark-to`).hide();
            $(`${selectorPrefix} button.unmark`).show();
            $(`${selectorPrefix} span.signed-count`).text(data.signedCount);
          }
        }
      });
    }

    function unmarkToEvent(eventParams) {
      let params = {
        ...defaultParams,
        ...eventParams
      };
      $.post({
        url: "{% url "vk_group_app:unmark-client" %}",
        data: params,
        success: function (data) {
          if (data.success) {
            let selectorArgs = eventParamsToSelector(eventParams);
            let selectorPrefix = `div.container ${selectorArgs}`;
            $(`${selectorPrefix} button.unmark`).hide();
            $(`${selectorPrefix} button.mark-to`).show();
            $(`${selectorPrefix} span.signed-count`).text(data.signedCount);
          }
        }
      });
    }

    function eventParamsToSelector(eventParams) {
      return `[data-event-year="${eventParams.year}"][data-event-month="${eventParams.month}"][data-event-day="${eventParams.day}"][data-event-class="${eventParams.eventClassId}"]`;
    }

    function eventDataToDict($event) {
      return {
        year: parseInt($event.data('event-year')),
        month: parseInt($event.data('event-month')),
        day: parseInt($event.data('event-day')),
        eventClassId: parseInt($event.data('event-class'))
      }
    }

    $(function () {
      VK.init(function () {
        setInterval(iframeResize(), 500);
        $('button.mark-to').click(function () {
          markToEvent(eventDataToDict($(this).parents('div.container')));
        });
        $('button.unmark').click(function () {
          unmarkToEvent(eventDataToDict($(this).parents('div.container')));
        });
        $('#save-meta').click(function () {
          let $formAdminError = $('#form-admin-error');
          $formAdminError.hide();
          let params = {
            ...defaultParams
          };
          params.accessToken = $('#access-token').val();
          params.botConfirm = $('#bot-confirm').val();
          if (!params.accessToken || !params.botConfirm) {
            $formAdminError.find('div.msg_text').text('Заполните все поля!');
            $formAdminError.show();
            return;
          }

          $.post({
            url: "{% url "vk_group_app:bot-params" %}",
            data: params,
            success: function (data) {
              if (data.success) {
                $('#admin-params-save').show();
              } else {
                $formAdminError.find('div.msg_text').text(data.error || 'Ошибка связи');
                $formAdminError.show();
              }
            }
          });
        });
        $('#bot-options').click(function() {
          $('#bot-options-panel').toggle();
        });
      }, function () {
      }, '5.92');
    });
  </script>
</head>

<body>
{% if is_admin %}
  <div class="container" id="admin-data">
    {% if not has_company %}
      <div class="msg error">
        <div class="msg_text">
          Сообщество не привязано к компании в sportadmin.ru, по этому работа
          приложения сейчас не возможна. Для того, чтобы приложение было
          активировано передейте пожалуйста администратору sportadmin.ru
          слудуюший параметр:
          <br><br>
          Код группы ВК: <strong>{{ vk_group }}</strong>
        </div>
      </div>
    {% else %}
      {% if not has_access_token %}
        <div class="msg error">
          <div class="msg_text">
            Отлично, сообщество привязно к компании на sportadmin.ru и теперь
            расписание занятий и запись работает, но осталась
            одна проблема - мы не можем посылать сообщения клиентам от имени
            сообщества. Для того, чтоб бот нашего сервиса мог писать сообщения
            нужно сделать несколько действий:
            <ul>
              <li>Создать ключ доступа с правом на сообщение</li>
              <li>На странице "Callback API" получить "Строку, которую должен
                вернуть сервер"
              </li>
              <li>Сохранить эти два параметра в форме ниже.</li>
              <li>Добавить в адрес сервера:
                <strong>https://sportadmin.ru/bot/gl</strong> и нажать
                подтвердить.
              </li>
            </ul>
            <br><br>
            <div style="text-align: center">
              <a
                class="flat_button"
                href="https://vk.com/club{{ vk_group }}?act=tokens"
                target="_blank"
              >Создать ключ доступа и настроить бота</a>
            </div>
          </div>
        </div>
        <div class="msg ok_msg" id="admin-params-save" style="display: none;">
          <div class="msg_text">
            Отлично, важные данные для бота сохранены. Теперь осталось только
            написать правильный адрес бота
            <strong>https://sportadmin.ru/bot/gl</strong> нажать кнопку
            "подтвердить". После этого бот сможет отвечать на сообщения
            клиентов, и рассылать уведомления.
          </div>
        </div>
      {% endif %}
      <div class="row">
      <div class="col-10"></div>
      <div class="col-2" style="cursor: pointer; color: #2a5885; font-size: 13px; text-align: right;" id="bot-options">
        Опции бота
      </div>
      </div>
      <div
        class="container page_block_content"
        style="{% if has_access_token %}display: none;{% endif %}"
        id="bot-options-panel"
      >
        <div class="msg error" id="form-admin-error" style="display: none;">
          <div class="msg_text"></div>
        </div>
        <div class="row">
          <div class="col-5">
            <label for="access-token">Ключ доступа</label>
          </div>
          <div class="col-5">
            <input type="text" id="access-token" style="width: 100%;" value="{{ vk_access_token|default_if_none:'' }}">
          </div>
        </div>
        <div class="row">
          <div class="col-5">
            <label for="bot-confirm">Строка, которую должен вернуть сервер</label>
          </div>
          <div class="col-5">
            <input type="text" id="bot-confirm" style="width: 100%;" value="{{ vk_confirmation_token|default_if_none:'' }}">
          </div>
        </div>
        <div class="row" style="text-align: center">
          <button class="flat_button" id="save-meta">Сохранить настройки бота
          </button>
        </div>
      </div>
    {% endif %}
  </div>
{% endif %}
<div class="container" id="main-data">
  {% for event in events %}
    <div class="page_block row">
      <div class="page_block_sub_header">
        {% if is_admin %}
          <a href="{% url "crm:manager:event-class:event:event-by-date" event.event_class_id  event.date.year event.date.month event.date.day %}" target="_blank">{{ event.date|date:"l" }} / {{ event.event_class.name }}</a>
        {% else %}
          <span>{{ event.date|date:"l" }} / {{ event.event_class.name }}</span>
        {% endif %}
      </div>
      <div
        class="page_block_content container"
        data-event-year="{{ event.date|date:"Y" }}"
        data-event-month="{{ event.date|date:"n" }}"
        data-event-day="{{ event.date|date:"j" }}"
        data-event-class="{{ event.event_class_id }}"
      >
        <div class="row">
          <div class="col-9 container">
            <div class="row">
              <div class="col-6 info" title="Дата и время тренировки"><i
                class="far fa-clock"
              ></i>{{ event.date|date:"d b" }}
                ({{ event.start_time|date:"H:i" }}
                - {{ event.end_time|date:"H:i" }})
              </div>
              <div class="col-6 info" title="Место проведения тренировки"><i
                class="fas fa-map-marker-alt"
              ></i>{{ event.event_class.location }}</div>
            </div>
            <div class="row">
              <div class="col-6 info" title="Стоимость разового посещения">
                {% with ec_id=event.event_class_id %}
                  {% with price=ec_otv_price|get_value:ec_id %}
                    {% if price %}
                      <i class="fas fa-coins"></i>
                      {{ price|floatformat:"-2"|intcomma }} ₽
                    {% endif %}
                  {% endwith %}
                {% endwith %}
              </div>
              <div class="col-6 info" title="Тренер"><i
                class="fas fa-stopwatch"
              ></i>{{ event.event_class.coach }}</div>
            </div>
            <div class="row">
              <div class="col-6 info">
                <i class="fas fa-users"></i>
                <span class="signed-count">
                {% with count=event_signed_count|get_value:event.id|default:0 %}
                  {% pluralize count 'Записалcя' 'Записалось' 'Записалось' %}
                  {{ count }}
                  {% pluralize count 'человек' 'человека' 'человек' %}
                {% endwith %}
                </span>
              </div>
            </div>
          </div>
          <div class="col-3">
            <button
              class="flat_button secondary unmark"
              style="{% if event.id not in my_events %}display: none;{% endif %}"
            >
              Отменить запись
            </button>
            <button
              class="flat_button mark-to"
              style="{% if event.id in my_events %}display: none;{% endif %}"
            >
              Записаться
            </button>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
</body>
</html>